apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-aws-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hexianqing92-ui/node-aws-api.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: node-aws-api-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
