apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-aws-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-aws-api
  template:
    metadata:
      labels:
        app: node-aws-api
    spec:
      containers:
        - name: api
          image: node-aws-api
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: DATABASE_SSL
              value: disable
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: node-aws-api-env
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
